# Generated by Django 5.1.4 on 2025-01-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_xcoord_safespace_x_rename_ycoord_safespace_y_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('info', models.CharField(default='default_info', max_length=255)),
                ('campus', models.CharField(default='default_campus', max_length=255)),
            ],
        ),
    ]
