# Generated by Django 5.1.4 on 2025-04-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_path_task_pathpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(default='Recepción QR', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TotemQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(default='Totem QR', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SafeSpace',
        ),
        migrations.DeleteModel(
            name='StartingPoint',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
