# Generated by Django 5.1.4 on 2025-04-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_receptionqr_totemqr_delete_safespace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionqr',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='receptionqr',
            name='imageUrl',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='totemqr',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='totemqr',
            name='imageUrl',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
