# Generated by Django 5.1.4 on 2025-04-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_receptionqr_description_receptionqr_imageurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='campus',
            field=models.CharField(default='default_campus', max_length=255),
        ),
    ]
