# Generated by Django 5.1.4 on 2025-04-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_path_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionqr',
            name='campus',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='totemqr',
            name='campus',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='path',
            name='campus',
            field=models.CharField(default='', max_length=255),
        ),
    ]
