# Generated by Django 5.1.4 on 2025-04-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_receptionqr_campus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_incidente', models.CharField(max_length=100)),
                ('fecha_incidente', models.DateField()),
                ('lugar_incidente', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('anonimo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
