# Generated by Django 5.1.4 on 2025-04-25 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_denuncia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='anonimo',
        ),
    ]
