# Generated by Django 5.1.4 on 2025-04-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_denuncia_anonimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionqr',
            name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='totemqr',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='receptionqr',
            name='schedule',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='receptionqr',
            name='status',
            field=models.CharField(choices=[('Operativo', 'Operativo'), ('No Operativo', 'No Operativo')], default='Operativo', max_length=20),
        ),
        migrations.AddField(
            model_name='totemqr',
            name='status',
            field=models.CharField(choices=[('Operativo', 'Operativo'), ('No Operativo', 'No Operativo')], default='Operativo', max_length=20),
        ),
    ]
