# Generated by Django 5.1.4 on 2025-04-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0013_remove_receptionqr_imageurl_remove_totemqr_imageurl_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receptionqr",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="totemqr",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
