# Generated by Django 5.1.4 on 2025-05-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionqr',
            name='qr_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='totemqr',
            name='qr_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
