# Generated by Django 5.1.4 on 2025-05-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_receptionqr_qr_image_totemqr_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='campus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
