# Generated by Django 5.1.4 on 2025-05-20 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_userprofile_campus_userprofile_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='encargado_acogida',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to=settings.AUTH_USER_MODEL,null=True,),
            
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='campus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='lugar_incidente',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='telefono',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='tipo_incidente',
            field=models.CharField(choices=[('Acoso_sexual', 'Acoso Sexual'), ('Violencia_fisica', 'Violencia Física'), ('Violencia_psicologica', 'Violencia Psicológica'), ('Discriminacion', 'Discriminación de Género'), ('No estoy seguro necesito orientación', 'Otro')], default='', max_length=100),
        ),
    ]
