# Generated by Django 5.1.4 on 2025-05-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_denuncia_encargado_acogida_denuncia_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('tomada', 'Tomada')], default='pendiente', max_length=20),
        ),
    ]
