# Generated by Django 5.1.4 on 2025-05-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_denuncia_comentarios_denuncia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('motivos_no_atencion', models.JSONField()),
                ('comentarios', models.TextField(blank=True)),
                ('campus', models.CharField(max_length=100)),
                ('tipo_reporte', models.CharField(default='falta_atencion', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
