# Generated by Django 5.1.4 on 2025-05-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_reporteatencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteatencion',
            name='estado',
            field=models.CharField(default='nuevo', max_length=20),
        ),
    ]
