# Generated by Django 5.1.4 on 2025-06-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_reporteatencion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionqr',
            name='schedule',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
