# Generated by Django 5.1.4 on 2025-06-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_receptionqr_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='totemqr',
            name='qr_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
